vim.api.nvim_create_autocmd("ColorScheme", {
	callback = function()
		-- vim.api.nvim_set_hl(0, "String", { fg = "#99ffe4" })
		-- vim.api.nvim_set_hl(0, "Function", { fg = "#ffc391" })
		-- vim.api.nvim_set_hl(0, "Tag", { link = "Function" })
		-- vim.api.nvim_set_hl(0, "@type", { link = "Function" })
		-- vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1f1f1f" })
		-- vim.api.nvim_set_hl(0, "IncSearch", { bg = "#2f2f2f" })
		-- vim.api.nvim_set_hl(0, "CurSearch", { bg = "#4f4f4f" })
		-- vim.api.nvim_set_hl(0, "Number", { fg = "#ffffff", bold = false })
		-- vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", { bg = "#89d9c2", fg = "#101010" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpMenu", { link = "Normal" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { link = "Normal" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpDoc", { link = "Normal" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { link = "Normal" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpDocSeparator", { link = "Normal" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpKind", { link = "Normal" })
		-- vim.api.nvim_set_hl(0, "BlinkCmpSource", { link = "Normal" })
	end,
})
